/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ofirbd.linkbudget;

import java.text.DecimalFormat;

import javax.swing.JInternalFrame;


/**
 *
 * @author ofirbd
 */
public class LinkBudgetGUI extends javax.swing.JFrame {

    // objects
    LinkBudgetMain linkbudgetMain = null;
    
    DecimalFormat df = new DecimalFormat("##.#");
    
    /**
     * Creates new form RF_Propagation_GUI
     */
    public LinkBudgetGUI() {
        initComponents();
        initApp();
    }
    
    private void initApp(){
        linkbudgetMain = new LinkBudgetMain(this);
        
        buttonGroup_rx.add(jRadioButton_sensitivity);
        buttonGroup_rx.add(jRadioButton_snr);
        
        buttonGroup_linkReliability.add(jRadioButton_R50);
        buttonGroup_linkReliability.add(jRadioButton_R90);
        buttonGroup_linkReliability.add(jRadioButton_R99);
        
        buttonGroup_chartType.add(jToggleButton_fadeMarginChart);
        buttonGroup_chartType.add(jToggleButton_pathLossChart);
        buttonGroup_chartType.add(jToggleButton_rslChart);
        
        if(jRadioButton_sensitivity.isSelected()){
            jTextField_snr.setEnabled(false);
            jTextField_rxSensitivity.setEnabled(true);
        }else {
            jTextField_snr.setEnabled(true);
            jTextField_rxSensitivity.setEnabled(false);
        }
        
        if(jComboBox_propagationModel.getSelectedItem().equals("Hata")){
            jLabel_hataType.setVisible(true);
             jComboBox_hataType.setVisible(true);
       }else{
            jLabel_hataType.setVisible(false);
            jComboBox_hataType.setVisible(false);
            
        }
        
        if(jComboBox_propagationModel.getSelectedItem().equals("Log-Distance")){
            jLabel_flatFadingAttn.setVisible(true);
            jLabel_pathLossExp.setVisible(true);
            jTextField_pathLossExp.setVisible(true);
            jTextField_flatFadingAttn.setVisible(true);
            jLabel_flatFadingAttnUnits.setVisible(true);
            jTextField_d0PathLoss.setVisible(true);
            jTextField_d0.setVisible(true);
            jLabel_d0.setVisible(true);
            jLabel_d0PathLoss.setVisible(true);
            jLabel_d0PathLossUnits.setVisible(true);
            jLabel_d0Units.setVisible(true);
        }else{
            jLabel_flatFadingAttn.setVisible(false);
            jLabel_pathLossExp.setVisible(false);
            jTextField_pathLossExp.setVisible(false);
            jTextField_flatFadingAttn.setVisible(false);
            jLabel_flatFadingAttnUnits.setVisible(false);
            jTextField_d0PathLoss.setVisible(false);
            jTextField_d0.setVisible(false);
            jLabel_d0.setVisible(false);
            jLabel_d0PathLoss.setVisible(false);
            jLabel_d0PathLossUnits.setVisible(false);
            jLabel_d0Units.setVisible(false);
        }
            
        
        if(jRadioButton_radioSettings.isSelected()){
            jLabel_linkBudget.setEnabled(false);
            jLabel_linkBudgetUnit.setEnabled(false);
            jTextField_linkBudget.setEnabled(false);
            jLabel_Gb.setVisible(true);
            jLabel_GbUnit.setVisible(true);
            jTextField_Gb.setVisible(true);
            jLabel_Gm.setVisible(true);
            jLabel_GmUnit.setVisible(true);
            jTextField_Gm.setVisible(true);
            jPanel4.setVisible(true);
            jPanel5.setVisible(true);
            jTextField_dataRate.setVisible(true);
            jLabel_dataRateUnit.setVisible(true);
            jLabel_dataRate.setVisible(true);
        }else{
            jLabel_linkBudget.setEnabled(true);
            jLabel_linkBudgetUnit.setEnabled(true);
            jTextField_linkBudget.setEnabled(true);
            jLabel_Gb.setVisible(false);
            jLabel_GbUnit.setVisible(false);
            jTextField_Gb.setVisible(false);
            jLabel_Gm.setVisible(false);
            jLabel_GmUnit.setVisible(false);
            jTextField_Gm.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jTextField_dataRate.setVisible(false);
            jLabel_dataRateUnit.setVisible(false);
            jLabel_dataRate.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_hataModels = new javax.swing.ButtonGroup();
        buttonGroup_rx = new javax.swing.ButtonGroup();
        buttonGroup_chartType = new javax.swing.ButtonGroup();
        buttonGroup_linkReliability = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox_propagationModel = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField_foliageDepth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton_R90 = new javax.swing.JRadioButton();
        jRadioButton_R50 = new javax.swing.JRadioButton();
        jRadioButton_R99 = new javax.swing.JRadioButton();
        jLabel_pathLossExp = new javax.swing.JLabel();
        jTextField_pathLossExp = new javax.swing.JTextField();
        jLabel_flatFadingAttn = new javax.swing.JLabel();
        jTextField_flatFadingAttn = new javax.swing.JTextField();
        jLabel_flatFadingAttnUnits = new javax.swing.JLabel();
        jLabel_hataType = new javax.swing.JLabel();
        jComboBox_hataType = new javax.swing.JComboBox();
        jLabel_d0 = new javax.swing.JLabel();
        jLabel_d0PathLoss = new javax.swing.JLabel();
        jTextField_d0 = new javax.swing.JTextField();
        jTextField_d0PathLoss = new javax.swing.JTextField();
        jLabel_d0Units = new javax.swing.JLabel();
        jLabel_d0PathLossUnits = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResults = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_notes = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_transmitPower = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Gb = new javax.swing.JLabel();
        jTextField_Gb = new javax.swing.JTextField();
        jLabel_GbUnit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_txLoss = new javax.swing.JTextField();
        jLabel_linkBudgetUnit1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_NF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_BW = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton_sensitivity = new javax.swing.JRadioButton();
        jRadioButton_snr = new javax.swing.JRadioButton();
        jTextField_rxSensitivity = new javax.swing.JTextField();
        jTextField_snr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel_Gm = new javax.swing.JLabel();
        jTextField_Gm = new javax.swing.JTextField();
        jLabel_GmUnit = new javax.swing.JLabel();
        jLabel_linkBudgetUnit2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_rxLoss = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel_dataRate = new javax.swing.JLabel();
        jTextField_dataRate = new javax.swing.JTextField();
        jLabel_dataRateUnit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_centerFreq = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton_radioSettings = new javax.swing.JRadioButton();
        jLabel_linkBudget = new javax.swing.JLabel();
        jTextField_linkBudget = new javax.swing.JTextField();
        jLabel_linkBudgetUnit = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_requiredLinkDistance = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_hb = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_hm = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton_pathLossChart = new javax.swing.JToggleButton();
        jToggleButton_fadeMarginChart = new javax.swing.JToggleButton();
        jToggleButton_rslChart = new javax.swing.JToggleButton();
        jButton_calc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_saveResults = new javax.swing.JMenuItem();
        jMenuItem_saveSummary = new javax.swing.JMenuItem();
        jMenuItem_exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radio Propagation Calculator v15.3.1");
        setPreferredSize(new java.awt.Dimension(1000, 760));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propagation Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12))); // NOI18N

        jLabel23.setText("Propagation Model");

        jComboBox_propagationModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hata", "Egli", "Log-Distance", "Plane-Earth" }));
        jComboBox_propagationModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_propagationModelActionPerformed(evt);
            }
        });

        jLabel24.setText("Depth of Foliage");

        jLabel25.setText("m");

        jTextField_foliageDepth.setText("0");

        jLabel4.setText("Link Reliability");

        jRadioButton_R90.setText("90%");
        jRadioButton_R90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_R90ActionPerformed(evt);
            }
        });

        jRadioButton_R50.setText("50%");
        jRadioButton_R50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_R50ActionPerformed(evt);
            }
        });

        jRadioButton_R99.setSelected(true);
        jRadioButton_R99.setText("99%");
        jRadioButton_R99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_R99ActionPerformed(evt);
            }
        });

        jLabel_pathLossExp.setText("Path-loss exponent");

        jTextField_pathLossExp.setText("3.5");

        jLabel_flatFadingAttn.setText("Flat-Fading Attn");

        jTextField_flatFadingAttn.setText("0");

        jLabel_flatFadingAttnUnits.setText("dB");

        jLabel_hataType.setText("Hata Type");

        jComboBox_hataType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Large City", "Small City", "Suburban", "Open" }));
        jComboBox_hataType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_hataTypeActionPerformed(evt);
            }
        });

        jLabel_d0.setText("Distance d0");

        jLabel_d0PathLoss.setText("d0 Path Loss");

        jTextField_d0.setText("1");

        jTextField_d0PathLoss.setText("100");

        jLabel_d0Units.setText("km");

        jLabel_d0PathLossUnits.setText("dB");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel_pathLossExp)
                    .addComponent(jLabel_flatFadingAttn)
                    .addComponent(jLabel_d0)
                    .addComponent(jLabel_d0PathLoss)
                    .addComponent(jLabel24)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_hataType))
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_propagationModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_hataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_pathLossExp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_flatFadingAttn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_d0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_d0PathLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_foliageDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel_d0PathLossUnits)
                    .addComponent(jLabel_d0Units)
                    .addComponent(jLabel_flatFadingAttnUnits))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jRadioButton_R50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_R90)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_R99)
                .addGap(6, 6, 6))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBox_propagationModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox_hataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_hataType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pathLossExp)
                    .addComponent(jTextField_pathLossExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_flatFadingAttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_flatFadingAttn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_flatFadingAttnUnits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_d0, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_d0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_d0Units))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_d0PathLoss)
                    .addComponent(jTextField_d0PathLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_d0PathLossUnits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField_foliageDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(9, 9, 9)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton_R50)
                    .addComponent(jRadioButton_R90)
                    .addComponent(jRadioButton_R99)))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textResults.setEditable(false);
        textResults.setColumns(20);
        textResults.setRows(5);
        textResults.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Results Summary"));
        jScrollPane1.setViewportView(textResults);

        jTextArea_notes.setEditable(false);
        jTextArea_notes.setColumns(20);
        jTextArea_notes.setRows(5);
        jTextArea_notes.setAutoscrolls(false);
        jTextArea_notes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Notes"));
        jScrollPane3.setViewportView(jTextArea_notes);
        jTextArea_notes.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Path Loss", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transmitter Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12))); // NOI18N

        jLabel1.setText("Transmit Power");

        jTextField_transmitPower.setText("34");

        jLabel2.setText("dBm");

        jLabel_Gb.setText("Tx Antenna Gain (Gb)");

        jTextField_Gb.setText("0");

        jLabel_GbUnit.setText("dBi");

        jLabel7.setText("Tx Loss");

        jTextField_txLoss.setText("0");

        jLabel_linkBudgetUnit1.setText("dB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Gb)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Gb)
                    .addComponent(jTextField_transmitPower, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jTextField_txLoss))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_GbUnit)
                    .addComponent(jLabel_linkBudgetUnit1))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_transmitPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_Gb)
                    .addComponent(jTextField_Gb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_GbUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_txLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_linkBudgetUnit1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receiver Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12))); // NOI18N

        jLabel6.setText("Noise Figure");

        jTextField_NF.setText("6");

        jLabel3.setText("Bandwidth");

        jTextField_BW.setText("6");
        jTextField_BW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BWActionPerformed(evt);
            }
        });

        jLabel9.setText("kHz");

        jLabel11.setText("dB");

        jRadioButton_sensitivity.setSelected(true);
        jRadioButton_sensitivity.setText("Rx Sensitivity Threshold");
        jRadioButton_sensitivity.setToolTipText("the minimum received signal level that will provide reliable operation");
        jRadioButton_sensitivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_sensitivityActionPerformed(evt);
            }
        });

        jRadioButton_snr.setText("SNR");
        jRadioButton_snr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_snrActionPerformed(evt);
            }
        });

        jTextField_rxSensitivity.setText("-120");
        jTextField_rxSensitivity.setToolTipText("the minimum received signal level that will provide reliable operation");

        jTextField_snr.setText("10");

        jLabel12.setText("dBm");

        jLabel22.setText("dB");

        jLabel_Gm.setText("Rx Antenna Gain (Gm)");

        jTextField_Gm.setText("0");

        jLabel_GmUnit.setText("dBi");

        jLabel_linkBudgetUnit2.setText("dB");

        jLabel8.setText("Rx Loss");

        jTextField_rxLoss.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Gm)
                    .addComponent(jRadioButton_snr)
                    .addComponent(jRadioButton_sensitivity)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_rxLoss, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jTextField_snr)
                    .addComponent(jTextField_rxSensitivity, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jTextField_BW)
                    .addComponent(jTextField_NF)
                    .addComponent(jTextField_Gm))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_GmUnit)
                    .addComponent(jLabel_linkBudgetUnit2)
                    .addComponent(jLabel22)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_NF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_BW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioButton_sensitivity)
                    .addComponent(jTextField_rxSensitivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioButton_snr)
                    .addComponent(jTextField_snr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_rxLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_linkBudgetUnit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_Gm)
                    .addComponent(jTextField_Gm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_GmUnit)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Modem Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12))); // NOI18N

        jLabel_dataRate.setText("Data Rate");
        jLabel_dataRate.setEnabled(false);

        jTextField_dataRate.setEnabled(false);

        jLabel_dataRateUnit.setText("kbps");
        jLabel_dataRateUnit.setEnabled(false);

        jLabel5.setText("Center Frequency");

        jTextField_centerFreq.setText("470");

        jLabel10.setText("MHz");

        jRadioButton_radioSettings.setSelected(true);
        jRadioButton_radioSettings.setText("Set via Radio Settings");
        jRadioButton_radioSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_radioSettingsActionPerformed(evt);
            }
        });

        jLabel_linkBudget.setText("Link Budget");

        jTextField_linkBudget.setText("150");

        jLabel_linkBudgetUnit.setText("dB");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_radioSettings)
                    .addComponent(jLabel_linkBudget)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_dataRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_dataRate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_centerFreq, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_dataRateUnit)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextField_linkBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_linkBudgetUnit)))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dataRate)
                    .addComponent(jTextField_dataRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dataRateUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_centerFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_linkBudget)
                    .addComponent(jTextField_linkBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_linkBudgetUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_radioSettings)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Link Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 1, 12))); // NOI18N

        jLabel28.setText("Required Link Distance");

        jTextField_requiredLinkDistance.setText("1");

        jLabel19.setText("km");

        jLabel17.setText("Transmitter Antenna Height (hb)");

        jTextField_hb.setText("20");

        jLabel20.setText("m");

        jLabel18.setText("Receiver Antenna Height (hm)");

        jTextField_hm.setText("1");

        jLabel21.setText("m");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel28))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_requiredLinkDistance)
                    .addComponent(jTextField_hb)
                    .addComponent(jTextField_hm, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_hb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_hm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel28)
                    .addComponent(jTextField_requiredLinkDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(574, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Link Settings", jPanel2);

        jToolBar1.setRollover(true);

        jToggleButton_pathLossChart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton_pathLossChart.setSelected(true);
        jToggleButton_pathLossChart.setText("pathLoss");
        jToggleButton_pathLossChart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton_pathLossChart.setFocusable(false);
        jToggleButton_pathLossChart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton_pathLossChart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton_pathLossChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_pathLossChartActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton_pathLossChart);

        jToggleButton_fadeMarginChart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton_fadeMarginChart.setText("fadeMargin");
        jToggleButton_fadeMarginChart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton_fadeMarginChart.setFocusable(false);
        jToggleButton_fadeMarginChart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton_fadeMarginChart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton_fadeMarginChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_fadeMarginChartActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton_fadeMarginChart);

        jToggleButton_rslChart.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton_rslChart.setText("RSL");
        jToggleButton_rslChart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton_rslChart.setFocusable(false);
        jToggleButton_rslChart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton_rslChart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton_rslChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_rslChartActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton_rslChart);

        jButton_calc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_calc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ofirbd/play.png"))); // NOI18N
        jButton_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_calc);

        jMenu1.setText("File");

        jMenuItem_saveResults.setText("Save Results");
        jMenuItem_saveResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_saveResultsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_saveResults);

        jMenuItem_saveSummary.setText("Save Summary");
        jMenuItem_saveSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_saveSummaryActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_saveSummary);

        jMenuItem_exit.setText("Exit");
        jMenuItem_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem1.setText("About");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_radioSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_radioSettingsActionPerformed
        if(jRadioButton_radioSettings.isSelected()){
            jLabel_linkBudget.setEnabled(false);
            jLabel_linkBudgetUnit.setEnabled(false);
            jTextField_linkBudget.setEnabled(false);
            jLabel_Gb.setVisible(true);
            jLabel_GbUnit.setVisible(true);
            jTextField_Gb.setVisible(true);
            jLabel_Gm.setVisible(true);
            jLabel_GmUnit.setVisible(true);
            jTextField_Gm.setVisible(true);
            jPanel4.setVisible(true);
            jPanel5.setVisible(true);
            jTextField_dataRate.setVisible(true);
            jLabel_dataRateUnit.setVisible(true);
            jLabel_dataRate.setVisible(true);
        }else{
            jLabel_linkBudget.setEnabled(true);
            jLabel_linkBudgetUnit.setEnabled(true);
            jTextField_linkBudget.setEnabled(true);
            jLabel_Gb.setVisible(false);
            jLabel_GbUnit.setVisible(false);
            jTextField_Gb.setVisible(false);
            jLabel_Gm.setVisible(false);
            jLabel_GmUnit.setVisible(false);
            jTextField_Gm.setVisible(false);
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jTextField_dataRate.setVisible(false);
            jLabel_dataRateUnit.setVisible(false);
            jLabel_dataRate.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton_radioSettingsActionPerformed

    private void jRadioButton_snrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_snrActionPerformed
        jTextField_rxSensitivity.setEnabled(false);
        jTextField_snr.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_snrActionPerformed

    private void jRadioButton_sensitivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_sensitivityActionPerformed
        jTextField_snr.setEnabled(false);
        jTextField_rxSensitivity.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_sensitivityActionPerformed

    private void jTextField_BWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BWActionPerformed

    private void jButton_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcActionPerformed
        setMain(); // set the parameters from the GUI
    }//GEN-LAST:event_jButton_calcActionPerformed

    private void jMenuItem_saveResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_saveResultsActionPerformed
    	linkbudgetMain.saveCsvResultsFile("results.csv");
    	
    }//GEN-LAST:event_jMenuItem_saveResultsActionPerformed

    private void jMenuItem_saveSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_saveSummaryActionPerformed
        saveResultsSummary("results_summary.txt");
    }//GEN-LAST:event_jMenuItem_saveSummaryActionPerformed

    private void jMenuItem_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_exitActionPerformed

    private void jToggleButton_pathLossChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_pathLossChartActionPerformed
        setMain();
    }//GEN-LAST:event_jToggleButton_pathLossChartActionPerformed

    private void jToggleButton_fadeMarginChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_fadeMarginChartActionPerformed
        setMain();
    }//GEN-LAST:event_jToggleButton_fadeMarginChartActionPerformed

    private void jToggleButton_rslChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_rslChartActionPerformed
        setMain();
    }//GEN-LAST:event_jToggleButton_rslChartActionPerformed

    private void jComboBox_hataTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_hataTypeActionPerformed
        setMain();
    }//GEN-LAST:event_jComboBox_hataTypeActionPerformed

    private void jRadioButton_R99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_R99ActionPerformed
        setMain();
    }//GEN-LAST:event_jRadioButton_R99ActionPerformed

    private void jRadioButton_R50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_R50ActionPerformed
        setMain();
    }//GEN-LAST:event_jRadioButton_R50ActionPerformed

    private void jRadioButton_R90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_R90ActionPerformed
        setMain();
    }//GEN-LAST:event_jRadioButton_R90ActionPerformed

    private void jComboBox_propagationModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_propagationModelActionPerformed
        if(jComboBox_propagationModel.getSelectedItem().equals("Hata")){
            jLabel_hataType.setVisible(true);
            jComboBox_hataType.setVisible(true);
        }else{
            jLabel_hataType.setVisible(false);
            jComboBox_hataType.setVisible(false);

        }

        if(jComboBox_propagationModel.getSelectedItem().equals("Log-Distance")){
            jLabel_flatFadingAttn.setVisible(true);
            jLabel_pathLossExp.setVisible(true);
            jTextField_pathLossExp.setVisible(true);
            jTextField_flatFadingAttn.setVisible(true);
            jLabel_flatFadingAttnUnits.setVisible(true);
            jTextField_d0PathLoss.setVisible(true);
            jTextField_d0.setVisible(true);
            jLabel_d0.setVisible(true);
            jLabel_d0PathLoss.setVisible(true);
            jLabel_d0PathLossUnits.setVisible(true);
            jLabel_d0Units.setVisible(true);
        }else{
            jLabel_flatFadingAttn.setVisible(false);
            jLabel_pathLossExp.setVisible(false);
            jTextField_pathLossExp.setVisible(false);
            jTextField_flatFadingAttn.setVisible(false);
            jLabel_flatFadingAttnUnits.setVisible(false);
            jTextField_d0PathLoss.setVisible(false);
            jTextField_d0.setVisible(false);
            jLabel_d0.setVisible(false);
            jLabel_d0PathLoss.setVisible(false);
            jLabel_d0PathLossUnits.setVisible(false);
            jLabel_d0Units.setVisible(false);
        }

        setMain();
    }//GEN-LAST:event_jComboBox_propagationModelActionPerformed

    private void saveResultsSummary(String outFile){
    	System.out.println(textResults.getText());
    	Utils.fprintf(outFile, String.format("Results Summary:\n%s", textResults.getText()),false);
    }
    
    private void setMain(){
    	// set variables from GUI
    	linkbudgetMain.setTransmitPower(Double.parseDouble(jTextField_transmitPower.getText()));
    	linkbudgetMain.setGb(Double.parseDouble(jTextField_Gb.getText()));
    	linkbudgetMain.setGm(Double.parseDouble(jTextField_Gm.getText()));
    	linkbudgetMain.setRxSensitivity(Double.parseDouble(jTextField_rxSensitivity.getText()));
    	linkbudgetMain.setBW(Double.parseDouble(jTextField_BW.getText()));
    	linkbudgetMain.setNF(Double.parseDouble(jTextField_NF.getText()));
    	linkbudgetMain.setFoliageDepth(Double.parseDouble(jTextField_foliageDepth.getText()));
    	linkbudgetMain.setfreq(Double.parseDouble(jTextField_centerFreq.getText()));
    	linkbudgetMain.setHb(Double.parseDouble(jTextField_hb.getText()));
    	linkbudgetMain.setHm(Double.parseDouble(jTextField_hm.getText()));
    	linkbudgetMain.setRequiredLinkDistance(Double.parseDouble(jTextField_requiredLinkDistance.getText()));
    	linkbudgetMain.setSnr(Double.parseDouble(jTextField_snr.getText()));
    	linkbudgetMain.setPropagationModel(jComboBox_propagationModel.getSelectedItem().toString());
    	linkbudgetMain.setTxLoss(Double.parseDouble(jTextField_txLoss.getText()));
    	linkbudgetMain.setRxLoss(Double.parseDouble(jTextField_rxLoss.getText()));
    	//if dataRate field is empty then set it to zero to avoid error
    	if(jTextField_dataRate.getText().isEmpty()){
    		linkbudgetMain.setDataRate(0);
    	}else{
    		linkbudgetMain.setDataRate(Double.parseDouble(jTextField_dataRate.getText()));
    	}
        // set log-distance parameters
        if(jComboBox_propagationModel.getSelectedItem().equals("Log-Distance")){
            linkbudgetMain.setD0(Double.parseDouble(jTextField_d0.getText()));
            linkbudgetMain.setPathLossAtd0(Double.parseDouble(jTextField_d0PathLoss.getText()));
            linkbudgetMain.setPathLossExp(Double.parseDouble(jTextField_pathLossExp.getText()));
            linkbudgetMain.setFlatFaddingAttn(Double.parseDouble(jTextField_flatFadingAttn.getText()));
        }
    	
    	
    	// set Hata type
        switch(jComboBox_hataType.getSelectedItem().toString()){
            case "Large City": linkbudgetMain.setHataType("urban");
                break;
            case "Small City": linkbudgetMain.setHataType("smallcity");
                break;
            case "Suburban": linkbudgetMain.setHataType("suburban");
                break;
            case "Open": linkbudgetMain.setHataType("rural");
                break;
            default: 
                break;
        }
        
    	// set link reliability
    	if(jRadioButton_R50.isSelected()){
    		linkbudgetMain.setReliability(50);
    	}else if(jRadioButton_R90.isSelected()){
    		linkbudgetMain.setReliability(90);
    	}else if(jRadioButton_R99.isSelected()){
    		linkbudgetMain.setReliability(99);
    	}
    	
    	// calculate the path loss
    	double linkPathLoss = linkbudgetMain.pathLossCalc();
    	
    	// calc link budget
    	boolean selectSNR = jRadioButton_snr.isSelected();
    	boolean reasonableSensitivity = linkbudgetMain.linkMarginCalc(linkPathLoss, selectSNR); // calculate the link margin
    	if(jRadioButton_radioSettings.isSelected()){
    		linkbudgetMain.setLinkBudget(linkbudgetMain.linkBudgetCalc()); // calculate the linkbudget from the radio settings parameters
    		
    	}else{
    		double linkBudget = Double.parseDouble(jTextField_linkBudget.getText());
    		linkbudgetMain.setLinkBudget(linkBudget);
    		double linkMargin = linkBudget - linkPathLoss;
    		linkbudgetMain.setLinkMargin(linkMargin);
    	}
    	
    	// find maximum link distance
    	double maxLinkDistance = linkbudgetMain.findMaxLinkDistance();
    	linkbudgetMain.setMaxLinkDistance(maxLinkDistance);

    	// print notes
    	
    	if(jComboBox_propagationModel.getSelectedItem().equals("Hata")){
    		printNotes("The Hata model is an empirical formulation.\n150 < fc < 1500MHz\n30m < hb < 200m\n1km < d < 20km");
    	}else if(jComboBox_propagationModel.getSelectedItem().equals("Egli")){
    		printNotes("The Egli model is a simplified model for Terrain modeling\n based on empirical tests that assumes\n'gently rolling terrain with average hill heights\nof approximately 15 meters'\n40 < fc < 900MHz, d < 60km");
    	}else if(jComboBox_propagationModel.getSelectedItem().equals("Plane-Earth")){
    		printNotes("The Plane-Earth Ground Bounce model assumes a flat,\nsmooth and reflective ground surface.\nAlso called '2-Ray ground-reflection model'\n"
                        + "Assumptions: d*Lamda>>hb*hm, d>>hb, hm");
        }else if(jComboBox_propagationModel.getSelectedItem().equals("Log-Distance")){
                printNotes("The log-distance path loss model predicts the path loss\n a signal encounters inside a building\n or densely populated areas over distance.");
    	}

    	// print to screen
    	textResults.setText(""); // clear text screen
    	printResults("Propagation Model \t" + jComboBox_propagationModel.getSelectedItem());
    	if(jComboBox_propagationModel.getSelectedItem().equals("Hata")){
    		printResults(" " + linkbudgetMain.getHataType() + "\n");
    	}else{
    		printResults("\n");
    	}
    	//printResults("A flat, smooth and reflective ground surface is assumed\n");
            
    	printResults("Frequency \t" + linkbudgetMain.getfreq() + " MHz\n");
    	printResults("Required Link Distance \t" + linkbudgetMain.getRequiredLinkDistance() + " km\n");
    	printResults("Link Reliability \t" + linkbudgetMain.getReliability() + "%\n");
    	if(jRadioButton_radioSettings.isSelected()){
    		printResults("Link Budget \t" + df.format(linkbudgetMain.getLinkBudget()) + " dB\n");
        	printResults("Tx power \t" + linkbudgetMain.getTransmitPower() + " dBm\n");
        	printResults("EIRP \t" + linkbudgetMain.getEirp() + " dBm\n");
        	printResults("Path Loss \t" + df.format(linkbudgetMain.getTotalPathLoss()) + " dB\n");
        	printResults("Reliability Margin \t" + df.format(linkbudgetMain.getReliabilityMargin()) + " dB\n");
        	printResults("Rx Gain \t" + linkbudgetMain.getRxGain() + " dB\n");
        	printResults("Receive Signal Level " + df.format(linkbudgetMain.getRxSignalLevel()) + " dBm\n");
        	printResults("Receiver Noise Power " + df.format(linkbudgetMain.getNoisePower()) + " dBm\n");
        	printResults("Received SNR " + df.format(linkbudgetMain.getReceivedSNR()) + " dB\n");
        	printResults("Rx Sensitivity Threshold " + df.format(linkbudgetMain.getRxSensitivity()) + " dBm\n");
        	if(!reasonableSensitivity){
        		printResults("\n*Warning: receiver sensitivity threshold below noise power\n");
        		printResults(" enter higher Rx Sensitivity value.\n");
        	}
    	}else{
    		printResults("Link Budget \t" + df.format(linkbudgetMain.getLinkBudget()) + " dB\n");
    		printResults("Path Loss \t" + df.format(linkbudgetMain.getTotalPathLoss()) + " dB\n");
    	}
    	printResults("Link Margin " + df.format(linkbudgetMain.getLinkMargin()) + " dB\n");
    	printResults("Maximum Link Distance " + df.format(linkbudgetMain.getMaxLinkDistance()) + " km\n");
    	printResults("Maximum Link Distance at " + linkbudgetMain.getReliability() + "% " + "Reliability "+ df.format(linkbudgetMain.getMaxLinkDistanceAtReliabilityMargin()) + " km\n");
    	
    	
    	// select chart type
    	String chartType;
    	if(jToggleButton_pathLossChart.isSelected()){
    		chartType = "pathLoss";
    	}else if(jToggleButton_fadeMarginChart.isSelected()){
    		chartType = "fadeMargin";
        }else if(jToggleButton_rslChart.isSelected()){
                chartType = "rsl";
    	}else{
    		chartType = "pathLoss"; // default
    	}
    	
    	// create chart
    	JInternalFrame iframeChart = linkbudgetMain.plotChart(jDesktopPane1.getSize(), chartType);
    	jDesktopPane1.add(iframeChart);
    	iframeChart.pack();
        iframeChart.setSize(jDesktopPane1.getWidth(),jDesktopPane1.getHeight());
        iframeChart.setVisible(true);
    	
//    	JInternalFrame iframeChart = linkbudgetMain.plotChart(jDesktopPane1.getSize());
//    	jDesktopPane1.add(iframeChart);
//    	iframeChart.pack();
//        iframeChart.setSize(jDesktopPane1.getWidth(),jDesktopPane1.getHeight());
//        iframeChart.setVisible(true);
    	//System.out.println(linkbudgetMain.getPropagationModel());
    }
    
    private void printResults(String str){
    	textResults.append(str);
    	System.out.println(str);
    }
    
    private void printNotes(String str){
    	jTextArea_notes.setText(""); // clear text screen
    	jTextArea_notes.append(str);
    	System.out.println(str);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinkBudgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinkBudgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinkBudgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkBudgetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinkBudgetGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_chartType;
    private javax.swing.ButtonGroup buttonGroup_hataModels;
    private javax.swing.ButtonGroup buttonGroup_linkReliability;
    private javax.swing.ButtonGroup buttonGroup_rx;
    private javax.swing.JButton jButton_calc;
    private javax.swing.JComboBox jComboBox_hataType;
    private javax.swing.JComboBox jComboBox_propagationModel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Gb;
    private javax.swing.JLabel jLabel_GbUnit;
    private javax.swing.JLabel jLabel_Gm;
    private javax.swing.JLabel jLabel_GmUnit;
    private javax.swing.JLabel jLabel_d0;
    private javax.swing.JLabel jLabel_d0PathLoss;
    private javax.swing.JLabel jLabel_d0PathLossUnits;
    private javax.swing.JLabel jLabel_d0Units;
    private javax.swing.JLabel jLabel_dataRate;
    private javax.swing.JLabel jLabel_dataRateUnit;
    private javax.swing.JLabel jLabel_flatFadingAttn;
    private javax.swing.JLabel jLabel_flatFadingAttnUnits;
    private javax.swing.JLabel jLabel_hataType;
    private javax.swing.JLabel jLabel_linkBudget;
    private javax.swing.JLabel jLabel_linkBudgetUnit;
    private javax.swing.JLabel jLabel_linkBudgetUnit1;
    private javax.swing.JLabel jLabel_linkBudgetUnit2;
    private javax.swing.JLabel jLabel_pathLossExp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_exit;
    private javax.swing.JMenuItem jMenuItem_saveResults;
    private javax.swing.JMenuItem jMenuItem_saveSummary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton_R50;
    private javax.swing.JRadioButton jRadioButton_R90;
    private javax.swing.JRadioButton jRadioButton_R99;
    private javax.swing.JRadioButton jRadioButton_radioSettings;
    private javax.swing.JRadioButton jRadioButton_sensitivity;
    private javax.swing.JRadioButton jRadioButton_snr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea_notes;
    private javax.swing.JTextField jTextField_BW;
    private javax.swing.JTextField jTextField_Gb;
    private javax.swing.JTextField jTextField_Gm;
    private javax.swing.JTextField jTextField_NF;
    private javax.swing.JTextField jTextField_centerFreq;
    private javax.swing.JTextField jTextField_d0;
    private javax.swing.JTextField jTextField_d0PathLoss;
    private javax.swing.JTextField jTextField_dataRate;
    private javax.swing.JTextField jTextField_flatFadingAttn;
    private javax.swing.JTextField jTextField_foliageDepth;
    private javax.swing.JTextField jTextField_hb;
    private javax.swing.JTextField jTextField_hm;
    private javax.swing.JTextField jTextField_linkBudget;
    private javax.swing.JTextField jTextField_pathLossExp;
    private javax.swing.JTextField jTextField_requiredLinkDistance;
    private javax.swing.JTextField jTextField_rxLoss;
    private javax.swing.JTextField jTextField_rxSensitivity;
    private javax.swing.JTextField jTextField_snr;
    private javax.swing.JTextField jTextField_transmitPower;
    private javax.swing.JTextField jTextField_txLoss;
    private javax.swing.JToggleButton jToggleButton_fadeMarginChart;
    private javax.swing.JToggleButton jToggleButton_pathLossChart;
    private javax.swing.JToggleButton jToggleButton_rslChart;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea textResults;
    // End of variables declaration//GEN-END:variables
}
